version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=siggaard
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ~/.config/postgres-data:/var/lib/postgresql/data
      - ~/.config/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
